"""poll deleted

Revision ID: 335bda1f3e0d
Revises: 7d6d9889785d
Create Date: 2021-06-19 10:00:52.624695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '335bda1f3e0d'
down_revision = '7d6d9889785d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('polls', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('polls', 'deleted')
    # ### end Alembic commands ###
